-- =====================================================================
-- Church Management: database schema, roles, row-level security, audit log
-- Run ONCE on a fresh Supabase project: Dashboard > SQL Editor > New query > paste > Run
--
-- Roles
--   admin      everything, manages users, deletes records
--   finance    reads/writes giving; reads members, attendance, departments, events
--   secretary  reads/writes members, attendance, departments, events; NO access to giving
--   viewer     read-only on everything except giving
--   pending    new sign-ups; no access to any data until an admin approves them
-- The FIRST account created becomes admin automatically. Everyone after that is 'pending'.
-- =====================================================================

-- ---------- profiles (one row per login) ----------
create table public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  email      text,
  full_name  text default '',
  role       text not null default 'pending'
             check (role in ('admin','finance','secretary','viewer','pending')),
  created_at timestamptz not null default now()
);
alter table public.profiles enable row level security;

-- Returns the caller's role. SECURITY DEFINER so policies can use it without recursion.
create or replace function public.app_role() returns text
language sql stable security definer set search_path = public as
$$ select role from public.profiles where id = auth.uid() $$;
revoke all on function public.app_role() from public, anon;
grant execute on function public.app_role() to authenticated;

create policy profiles_select on public.profiles for select to authenticated
  using (id = auth.uid() or public.app_role() = 'admin');
create policy profiles_update on public.profiles for update to authenticated
  using (public.app_role() = 'admin') with check (public.app_role() = 'admin');

-- Auto-create a profile when someone signs up. First user = admin, the rest = pending.
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id, new.email, coalesce(new.raw_user_meta_data->>'full_name', ''),
    case when exists (select 1 from public.profiles) then 'pending' else 'admin' end
  );
  return new;
end $$;
revoke all on function public.handle_new_user() from public, anon, authenticated;

create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------- data tables ----------
-- IDs are generated by the app (so records created offline can be synced safely).
create table public.members (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  phone      text,
  email      text,
  dob        date,
  gender     text check (gender in ('Male','Female')),
  grp        text,                       -- group / cell
  status     text not null default 'Active' check (status in ('Active','Inactive','Visitor')),
  address    text,
  notes      text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid default auth.uid()
);

create table public.attendance (
  id          uuid primary key default gen_random_uuid(),
  date        date not null,
  service     text not null,
  person_name text not null,
  status      text not null check (status in ('Present','Absent','Visitor')),
  note        text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  created_by  uuid default auth.uid()
);

create table public.giving (
  id         uuid primary key default gen_random_uuid(),
  date       date not null,
  giver      text not null default 'Anonymous',
  type       text not null check (type in ('Tithe','Offering','Donation','Pledge','Other')),
  amount     numeric(12,2) not null check (amount > 0),
  method     text not null check (method in ('Cash','Mobile Money','Bank','Card')),
  reference  text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid default auth.uid()
);

create table public.departments (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  leader     text,
  notes      text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid default auth.uid()
);

create table public.events (
  id          uuid primary key default gen_random_uuid(),
  title       text not null,
  date        date not null,
  event_time  text,
  location    text,
  description text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  created_by  uuid default auth.uid()
);

create index on public.members (name);
create index on public.attendance (date);
create index on public.giving (date);
create index on public.events (date);

-- keep updated_at fresh
create or replace function public.set_updated_at() returns trigger
language plpgsql as $$ begin new.updated_at = now(); return new; end $$;

do $$
declare t text;
begin
  foreach t in array array['members','attendance','giving','departments','events'] loop
    execute format('create trigger %I before update on public.%I for each row execute function public.set_updated_at()', t || '_updated_at', t);
  end loop;
end $$;

-- ---------- audit log (who changed what; admin-readable, view it in Supabase or add a page later) ----------
create table public.audit_log (
  id         bigint generated always as identity primary key,
  at         timestamptz not null default now(),
  actor      uuid default auth.uid(),
  table_name text not null,
  row_id     uuid,
  action     text not null,
  old_row    jsonb,
  new_row    jsonb
);
alter table public.audit_log enable row level security;
create policy audit_select on public.audit_log for select to authenticated
  using (public.app_role() = 'admin');

create or replace function public.audit_row() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'DELETE' then
    insert into public.audit_log (table_name, row_id, action, old_row) values (tg_table_name, old.id, tg_op, to_jsonb(old));
    return old;
  elsif tg_op = 'UPDATE' then
    insert into public.audit_log (table_name, row_id, action, old_row, new_row) values (tg_table_name, new.id, tg_op, to_jsonb(old), to_jsonb(new));
    return new;
  else
    insert into public.audit_log (table_name, row_id, action, new_row) values (tg_table_name, new.id, tg_op, to_jsonb(new));
    return new;
  end if;
end $$;
revoke all on function public.audit_row() from public, anon, authenticated;

do $$
declare t text;
begin
  foreach t in array array['members','attendance','giving','departments','events'] loop
    execute format('create trigger %I after insert or update or delete on public.%I for each row execute function public.audit_row()', t || '_audit', t);
  end loop;
end $$;

-- ---------- row-level security ----------
-- members / attendance / departments / events
do $$
declare t text;
begin
  foreach t in array array['members','attendance','departments','events'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format($p$create policy %I on public.%I for select to authenticated
      using (public.app_role() in ('admin','finance','secretary','viewer'))$p$, t || '_select', t);
    execute format($p$create policy %I on public.%I for insert to authenticated
      with check (public.app_role() in ('admin','secretary'))$p$, t || '_insert', t);
    execute format($p$create policy %I on public.%I for update to authenticated
      using (public.app_role() in ('admin','secretary'))
      with check (public.app_role() in ('admin','secretary'))$p$, t || '_update', t);
    execute format($p$create policy %I on public.%I for delete to authenticated
      using (public.app_role() = 'admin')$p$, t || '_delete', t);
  end loop;
end $$;

-- giving: financial data, only admin + finance
alter table public.giving enable row level security;
create policy giving_select on public.giving for select to authenticated
  using (public.app_role() in ('admin','finance'));
create policy giving_insert on public.giving for insert to authenticated
  with check (public.app_role() in ('admin','finance'));
create policy giving_update on public.giving for update to authenticated
  using (public.app_role() in ('admin','finance'))
  with check (public.app_role() in ('admin','finance'));
create policy giving_delete on public.giving for delete to authenticated
  using (public.app_role() = 'admin');

-- ---------- privileges (RLS above decides which rows) ----------
revoke all on public.profiles, public.members, public.attendance, public.giving,
              public.departments, public.events, public.audit_log from anon;
grant select, update on public.profiles to authenticated;
grant select, insert, update, delete on public.members, public.attendance, public.giving,
              public.departments, public.events to authenticated;
grant select on public.audit_log to authenticated;

-- Prevent duplicate attendance for the same person, service and date.
-- If applying to an existing database, run the cleanup/unique-index migration instead.
create unique index if not exists attendance_date_service_person_unique
  on public.attendance (date, service, lower(trim(person_name)));
